AllCops:
  TargetRubyVersion: 2.4.1

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
  - spec/**/*

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Enabled: false
