os: osx

language: ruby

rvm:
  - 2.4.3

addons:
  chrome: stable
  firefox: latest


cache:
  bundler: true

before_install:
  - sudo safaridriver --enable

install:
  - bundle install

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-darwin-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - bundle exec rubocop
  - bundle exec rspec

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT