os: osx

language: ruby

rvm:
  - 2.4.1

addons:
  chrome: stable
  firefox: latest


cache:
  bundler: true

before_install:
  - sudo safaridriver --enable

install:
  - bundle install

script:
  - bundle exec rubocop
  - bundle exec rspec